// client-react/src/components/TodoForm.tsx
import { Button, Flex, Input, Spinner } from "@chakra-ui/react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import React, { useState } from "react";
import { IoMdAdd } from "react-icons/io";
import { BASE_URL } from "../App";

const TodoForm = () => {
  const [newTodo, setNewTodo] = useState("");

  const queryClient = useQueryClient();

  const { mutate: createTodo, isPending: isCreating } = useMutation({
    mutationKey: ["createTodo"],
    mutationFn: async (e: React.FormEvent) => {
      e.preventDefault();
      try {
        const res = await fetch(BASE_URL + "/todos", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ body: newTodo }),
        });
        const data = await res.json();

        if (!res.ok) {
          throw new Error(data.error || "Something went wrong");
        }

        setNewTodo("");
        return data;
      } catch (error) {
        console.log(error);
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["todos"] });
    },
    onError: (error: Error) => {
      alert(error.message);
    },
  });

  return (
    <form onSubmit={createTodo}>
      <Flex gap={2}>
        <Input
          type="text"
          value={newTodo}
          onChange={(e) => setNewTodo(e.target.value)}
          ref={(input) => input && input.focus()}
        />
        <Button mx={2} type="submit" _active={{ transform: "scale(.97)" }}>
          {isCreating ? <Spinner size={"xs"} /> : <IoMdAdd size={30} />}
        </Button>
      </Flex>
    </form>
  );
};

export default TodoForm;

// client-solid/src/components/TodoForm.tsx
import { createMutation, useQueryClient } from "@tanstack/solid-query";
import { Component, createSignal } from "solid-js";
import { createTodo } from "../controllers/todos";
import { CgSpinner } from "solid-icons/cg";
import { IoAdd } from "solid-icons/io";

const TodoForm: Component = () => {
  const queryClient = useQueryClient();
  const [newTodo, setNewTodo] = createSignal("");

  const createTodoMutation = createMutation(() => ({
    mutationKey: ["createTodo"],
    mutationFn: async (e: SubmitEvent) => {
      e.preventDefault();
      await createTodo(newTodo());
    },
    onSuccess: () => {
      setNewTodo("");
      queryClient.invalidateQueries({ queryKey: ["todos"] });
    },
    onError: (error: Error) => {
      alert(error.message);
    },
  }));

  return (
    <form class="flex gap-4 justify-center items-center my-4" onSubmit={createTodoMutation.mutate}>
      <input
        class="input input-md input-bordered w-full max-w-xs"
        type="text"
        placeholder="Add things to do"
        value={newTodo()}
        onChange={(e) => setNewTodo(e.currentTarget.value)}
      />
      <button
        class="btn btn-square btn-primary active:scale-95"
        type="submit"
      >
        { createTodoMutation.isPending ? <CgSpinner class="animate-spin" size={30} /> : <IoAdd size={30} />}
      </button>
    </form>
  );
};

export default TodoForm;
