// client-solid/src/index.tsx
/* @refresh reload */
import { render } from 'solid-js/web'

import './index.css'
import App from './App'
import { ThemeProvider } from './providers/ThemeProvider'
import { QueryClient, QueryClientProvider } from '@tanstack/solid-query'

const queryClient = new QueryClient();

const root = document.getElementById('root')

render(() => (
  <QueryClientProvider client={queryClient}>
    <ThemeProvider mode='dark'>
      <App />
    </ThemeProvider>
  </QueryClientProvider>
), root!)

// client/src/main.tsx
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.tsx";
import "./index.css";
import { ChakraProvider } from "@chakra-ui/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import theme from "./chakra/theme.ts";

const queryClient = new QueryClient();

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <QueryClientProvider client={queryClient}>
      <ChakraProvider theme={theme}>
        <App />
      </ChakraProvider>
    </QueryClientProvider>
  </React.StrictMode>,
);
