// client-solid/src/components/Navbar.tsx
import { Component } from "solid-js";
import { modes, useTheme } from "../providers/ThemeProvider";
import solidLogo from "../assets/solid.svg";
import goLogo from "../assets/go.png";
import explodeIcon from "../assets/explode.png";
import { IoMoon, IoSunny } from "solid-icons/io";

const Navbar: Component = () => {
  const [colorMode, toggleTheme] = useTheme();

  return (
    <div class="navbar bg-base-100 justify-between max-w-[900px] mx-auto">
      <div class="flex items-center justify-center gap-3">
        <img class="w-12 h-12" src={solidLogo} alt="logo" />
        <p class="text-4xl">+</p>
        <img class="w-10" src={goLogo} alt="logo" />
        <p class="text-4xl">+</p>
        <img class="w-12 h-12" src={explodeIcon} alt="logo" />
      </div>
      <div class="flex items-center gap-3">
        <p class="text-lg font-medium">Daily Tasks</p>
        <button class="btn btn-outline" onClick={toggleTheme}>
          {colorMode() === modes.LIGHT ? <IoMoon /> : <IoSunny />}
        </button>
      </div>
    </div>
  );
};

export default Navbar;

// client-react/src/components/Navbar.tsx
import {
  Box,
  Button,
  Container,
  Flex,
  Text,
  useColorMode,
  useColorModeValue,
} from "@chakra-ui/react";
import { IoMoon } from "react-icons/io5";
import { LuSun } from "react-icons/lu";

const Navbar = () => {
  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <Container maxW={"900px"}>
      <Box
        bg={useColorModeValue("gray.400", "gray.700")}
        px={4}
        my={4}
        borderRadius={"5"}
      >
        <Flex h={16} alignItems={"center"} justifyContent={"space-between"}>
          {/* LEFT SIDE */}
          <Flex
            justifyContent={"center"}
            alignItems={"center"}
            gap={3}
            display={{ base: "none", sm: "flex" }}
          >
            <img src="/react.png" alt="logo" width={50} height={50} />
            <Text fontSize={"40"}>+</Text>
            <img src="/go.png" alt="logo" width={40} height={40} />
            <Text fontSize={"40"}>+</Text>
            <img src="/explode.png" alt="logo" width={50} height={50} />
          </Flex>

          {/* RIGHT SIDE */}
          <Flex alignItems={"center"} gap={3}>
            <Text fontSize={"lg"} fontWeight={500}>
              Daily Tasks
            </Text>
            {/* Toggle Color Mode */}
            <Button onClick={toggleColorMode}>
              {colorMode === "light" ? <IoMoon /> : <LuSun size={20} />}
            </Button>
          </Flex>
        </Flex>
      </Box>
    </Container>
  );
};

export default Navbar;
