// client-solid/src/components/TodoList.tsx
import { CgSpinner } from "solid-icons/cg";
import { Component, ErrorBoundary, For, Show, Suspense } from "solid-js";
import GoLogo from "../assets/go.png";
import TodoItem from "./TodoItem";
import { createQuery } from "@tanstack/solid-query";
import { Todo, fetchTodos } from "../controllers/todos";

const TodoList: Component = () => {
  const todosQuery = createQuery<Todo[]>(() => ({
    queryKey: ["todos"],
    queryFn: async () => {
      const todos = await fetchTodos();
      return todos;
    },
  }));

  return (
    <>
      <h1 class="text-transparent text-4xl uppercase font-bold text-center my-2 bg-gradient-to-l from-gray-700 to-gray-200 dark:from-blue-500 dark:to-blue-50 bg-clip-text">
        Today's Tasks
      </h1>
      <ErrorBoundary fallback={
        <div class="text-center">
          Error: {todosQuery.error?.message}
        </div>
      }>
        <Suspense fallback={
          <div class="flex justify-center my-4">
            <CgSpinner class="animate-spin" size={50} />
          </div>
        }>
          <div class="flex flex-col items-center mx-auto my-4 gap-2 max-w-[700px]">
            <Show when={todosQuery.data && todosQuery.data?.length <= 0}>
              <p class="text-xl">All task completed! 🤞</p>
              <img class="w-16" src={GoLogo} alt="Go logo" />
            </Show>
            <Show when={todosQuery.data && todosQuery.data.length > 0} >
              <For each={todosQuery.data || []}>
                {(todo) => (
                  <TodoItem todo={todo} />
                )}
              </For>
            </Show>
          </div>
        </Suspense>
      </ErrorBoundary>
    </>
  );
};

export default TodoList;

// client-react/src/components/TodoList.tsx
import { Flex, Spinner, Stack, Text } from "@chakra-ui/react";
import TodoItem from "./TodoItem";
import { useQuery } from "@tanstack/react-query";
import { BASE_URL } from "../App";

export type Todo = {
  id: number;
  body: string;
  completed: boolean;
}

const TodoList = () => {
  const {data: todos, isLoading} = useQuery<Todo[]>({
    queryKey: ["todos"],
    queryFn: async () => {
      try {
        const res = await fetch(BASE_URL + "/todos");
        const data = await res.json();

        if(!res.ok) {
          throw new Error(data.error || "Something went wrong");
        }

        return data || [];
      } catch (error) {
        console.log(error);
      }
    }
  });
  
  return (
    <>
      <Text
        fontSize={"4xl"}
        textTransform={"uppercase"}
        fontWeight={"bold"}
        textAlign={"center"}
        my={2}
        bgGradient={"linear(to-l, #0b85f8, #00ffff)"}
        bgClip={"text"}
      >
        Today's Tasks
      </Text>
      {isLoading && (
        <Flex justifyContent={"center"} my={4}>
          <Spinner size={"xl"} />
        </Flex>
      )}
      {!isLoading && todos?.length === 0 && (
        <Stack alignItems={"center"} my={4}>
          <Text fontSize={"xl"} textAlign={"center"} color={"gray.500"}>
            All tasks completed! 🤞
          </Text>
          <img src="/go.png" alt="Go logo" width={70} height={70} />
        </Stack>
      )}
      <Stack gap={3}>
        {todos?.map((todo) => <TodoItem key={todo.id} todo={todo} />)}
      </Stack>
    </>
  );
};

export default TodoList;
