// client-solid/src/components/TodoItem.tsx
import { Component, Show } from "solid-js";
import { Todo, deleteTodo, updateTodo } from "../controllers/todos";
import { IoCheckmarkCircle, IoTrash } from "solid-icons/io";
import { createMutation, useQueryClient } from "@tanstack/solid-query";

const TodoItem: Component<{ todo: Todo }> = (props) => {
  const queryClient = useQueryClient();

  const updateTodoMutation = createMutation(() => ({
    mutationKey: ["updateTodo"],
    mutationFn: async () => {
      await updateTodo(props.todo.id, !props.todo.completed);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["todos"] });
    },
  }));

  const deleteTodoMutation = createMutation(() => ({
    mutationKey: ["deleteTodo"],
    mutationFn: async () => {
      await deleteTodo(props.todo.id);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["todos"] });
    },
  }))

  return (
    <div class="flex items-center gap-2 w-full">
      <div class="flex grow items-center justify-between border border-gray-600 p-2 rounded-lg">
        <p>{props.todo.body}</p>
        <Show when={props.todo.completed}>
          <div class="badge badge-success gap-2 uppercase rounded-md px-1">
            done
          </div>
        </Show>
        <Show when={!props.todo.completed}>
          <div class="badge badge-warning gap-2 uppercase rounded-md px-1">
            in progress
          </div>
        </Show>
      </div>
      <div class="flex items-center gap-1">
        <button class="btn btn-sm btn-square" onClick={() => updateTodoMutation.mutate()}>
          <IoCheckmarkCircle size={20} />
        </button>
        <button class="btn btn-sm btn-square" onClick={() => deleteTodoMutation.mutate()}>
          <IoTrash size={20} />
        </button>
      </div>
    </div>
  );
};

export default TodoItem;

// client/src/components/TodoItem.tsx
import { Badge, Box, Flex, Spinner, Text } from "@chakra-ui/react";
import { FaCheckCircle } from "react-icons/fa";
import { MdDelete } from "react-icons/md";
import { Todo } from "./TodoList";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { BASE_URL } from "../App";

const TodoItem = ({ todo }: { todo: Todo }) => {
  const queryClient = useQueryClient();

  const { mutate: updateTodo, isPending: isUpdating } = useMutation({
    mutationKey: ["updateTodo"],
    mutationFn: async () => {
      if (todo.completed) {
        return alert("Todo is already completed");
      }

      try {
        const res = await fetch(BASE_URL + `/todos/${todo.id}`, {
          method: "PATCH",
        });
        const data = await res.json();

        if (!res.ok) {
          throw new Error(data.error || "Something went wrong");
        }

        return data;
      } catch (error) {
        console.log(error);
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["todos"] });
    },
  });

  const { mutate: deleteTodo, isPending: isDeleting } = useMutation({
    mutationKey: ["deleteTodo"],
    mutationFn: async () => {
      try {
        const res = await fetch(BASE_URL + `/todos/${todo.id}`, {
          method: "DELETE",
        });
        const data = await res.json();

        if (!res.ok) {
          throw new Error(data.error || "Something went wrong");
        }

        return data;
      } catch (error) {
        console.log(error);
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["todos"] });
    },
  });

  return (
    <Flex gap={2} alignItems={"center"}>
      <Flex
        flex={1}
        alignItems={"center"}
        border={"1px"}
        borderColor={"gray.600"}
        p={2}
        borderRadius={"lg"}
        justifyContent={"space-between"}
      >
        <Text
          color={todo.completed ? "green.200" : "yellow.100"}
          textDecoration={todo.completed ? "line-through" : "none"}
        >
          {todo.body}
        </Text>
        {todo.completed && (
          <Badge ml={"1"} colorScheme="green">
            Done
          </Badge>
        )}
        {!todo.completed && (
          <Badge ml={1} colorScheme="yellow">
            In Progress
          </Badge>
        )}
      </Flex>
      <Flex gap={2} alignItems={"center"}>
        <Box
          color={"green.500"}
          cursor={"pointer"}
          onClick={() => updateTodo()}
        >
          {!isUpdating && <FaCheckCircle size={20} />}
          {isUpdating && <Spinner size={"sm"} />}
        </Box>
        <Box
          color={"red.500"}
          cursor={"pointer"}
          onClick={() => deleteTodo()}
        >
          {!isDeleting && <MdDelete size={25} />}
          {isDeleting && <Spinner size={"sm"} />}
        </Box>
      </Flex>
    </Flex>
  );
};

export default TodoItem;
